name: Quality Gate Full Power

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
  ALLURE_RESULTS: "build/allure-results"
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}


jobs:
  run_tests_and_generate_report_v2:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout from the demo branch
        uses: actions/checkout@v4 # Get your repository's code
        with:
          ref: newsletter2512

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest # Ensure allure-pytest is installed

      - name: Run pytest tests with allure3
        run: | 
          npx allure run -- pytest